export * from './infrastructure/db/offers.schema';
export * from './domain/Offer';
export * from './domain/gateway/OffersProvider';
export * from './infrastructure/tmdb/TmdbOffersProvider';
export * from './application/queries/GetOffersHandler';
export * from './api/http/controllers/commerce.controller';
export * from './api/routes';
export * from './infrastructure/factories/commerce.factory';
export type { CommerceModuleConfig } from './infrastructure/factories/commerce.factory';
export * from './domain/service/AffiliateLinkService';
